version: '3'
services:
  client:
    container_name: habit_dev_client
    build: ./client
    image: debug_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
  api:
    container_name: habit_dev_api
    ports:
      - 3000:3000
    environment: 
      - PORT=3000
      - PGUSER=guymargalith
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=habit_tracker_dev
      - PGPORT=5432
      - NODE_ENV=dev
    depends_on: 
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"
  db:
    container_name: habit_dev_db
    expose:
      - "5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=habit_tracker_dev
      - POSTGRES_USER=guymargalith
      - POSTGRES_PASSWORD=password
volumes:
  dbdata: